services:
  api:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      psql_bp:
        condition: service_started
    environment:
      - DB_HOST=psql_bp

  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
