// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package devicedb

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type DeviceState string

const (
	DeviceStateAvailable DeviceState = "available"
	DeviceStateInUse     DeviceState = "in-use"
	DeviceStateInactive  DeviceState = "inactive"
)

func (e *DeviceState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceState(s)
	case string:
		*e = DeviceState(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceState: %T", src)
	}
	return nil
}

type NullDeviceState struct {
	DeviceState DeviceState
	Valid       bool // Valid is true if DeviceState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceState) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceState), nil
}

type Device struct {
	ID           string
	Name         string
	Brand        string
	State        DeviceState
	Creationtime time.Time
}
