// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package devicedb

import (
	"context"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	DeleteDevice(ctx context.Context, id string) (int64, error)
	GetDevice(ctx context.Context, id string) (Device, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
