// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package devicedb

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO device (name, brand, state)
VALUES ($1, $2, $3)
RETURNING id, name, brand, state, creationtime
`

type CreateDeviceParams struct {
	Name  string
	Brand string
	State DeviceState
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.Name, arg.Brand, arg.State)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.State,
		&i.Creationtime,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM device
WHERE ID = $1 AND State <> 'in-use'
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDevice = `-- name: GetDevice :one
SELECT ID, Name, Brand, State, CreationTime
FROM device
WHERE ID = $1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.State,
		&i.Creationtime,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT ID, Name, Brand, State, CreationTime
FROM device
WHERE ($1::text IS NULL OR brand = $1::text)
  AND ($2::device_state IS NULL OR state = $2::device_state)
ORDER BY CreationTime DESC
`

type ListDevicesParams struct {
	Brand sql.NullString
	State NullDeviceState
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.Brand, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.State,
			&i.Creationtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE device
SET Name = $2, Brand = $3, State = $4
WHERE ID = $1 AND State <> 'in-use'
RETURNING id, name, brand, state, creationtime
`

type UpdateDeviceParams struct {
	ID    string
	Name  string
	Brand string
	State DeviceState
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.Brand,
		arg.State,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.State,
		&i.Creationtime,
	)
	return i, err
}
